//Win64API.cpp
/* --------------------------------------------------------------------------------
 #
 #	Win64API.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Win32API
 #	author : dwaddell
 #	9/30/2019
 #
 # --------------------------------------------------------------------------------*/


#include "Win64API.h"
#include "Registry.h"


const char* const win32Commands[] = {
	"sys_GetRegEnum"
};

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	switch (selector)
	{
		case kInitPlugin:
			InitPlugin();
			break;

		case kDeinitPlugin:
			DeinitPlugin();
			break;

		case 1:
			sys_GetRegEnum(params);
			break;
	}	
}

void InitPlugin()
{
	// write initialisation code here...
}

void DeinitPlugin()
{
	// write deinitialisation code here...
}




