//Win64API.cpp
/* --------------------------------------------------------------------------------
 #
 #	Win64API.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Win32API
 #	author : dwaddell
 #	9/30/2019
 #
 # --------------------------------------------------------------------------------*/


#include "Win64API.h"
#include "Registry.h"
#include "WindowManagement.h"
#include "Miscellaneous.h"

const char* const win32Commands[] = {
	"sys_GetRegEnum"
	,"sys_GetRegText" // ACW 10/20/20 WIN-78 
	,"sys_GetRegLongint" // ACW 10/16/20 WIN-80
	,"gui_SetWindowTitleEx" // ACW 10/28/20 WIN-108
	,"gui_SetIconEX" // ACW 1/8/21 WIN-113
	,"gui_GetWindowStateEx" // ACW 1/11/21 WIN-109
	,"gui_ShowWindowEx" // ACW 1/14/21 WIN-112
	,"gui_DisableCloseBox" // ACW 1/14/21 WIN-114
	,"sys_PlayWav" // ACW 2/23/21 WIN-87
	,"sys_SetRegLongint" // ACW 3/8/21 WIN-97
	,"sys_SetRegText" // ACW 3/9/21 WIN-99
};

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	switch (selector)
	{
		case kInitPlugin:
			InitPlugin();
			break;

		case kDeinitPlugin:
			DeinitPlugin();
			break;

		case 1: // sys_GetRegEnum
			sys_GetRegEnum(params);
			break;

		case 2: // sys_GetRegText
		case 3: // sys_GetRegLongint
			// ACW 10/16/20 WIN-80
			sys_GetRegKey(params);
			break;

		case 4: // gui_setWindowTitleEx
			// ACW 10/28/20 WIN-108
			PA_RunInMainProcess((PA_RunInMainProcessProcPtr)gui_SetWindowTitleEx, params);
			break;

		case 5: // gui_setIconEX
			// ACW 1/8/21 WIN-113
			PA_RunInMainProcess((PA_RunInMainProcessProcPtr)gui_SetIconEx, params);
			break;

		case 6: // gui_GetWindowStateEx
			// ACW 1/11/21 WIN-109
			PA_RunInMainProcess((PA_RunInMainProcessProcPtr)gui_GetWindowStateEx, params);
			break;

		case 7: // gui_ShowWindowEx
			// ACW 1/14/21 WIN-112
			PA_RunInMainProcess((PA_RunInMainProcessProcPtr)gui_ShowWindowEx, params);
			break;

		case 8: // gui_DisableCloseBoxEx
			// ACW 1/14/21 WIN-114
			PA_RunInMainProcess((PA_RunInMainProcessProcPtr)gui_DisableCloseBoxEx, params);
			break;

		case 9: // sys_PlayWav
			// ACW 2/23/21 WIN-87
			sys_PlayWav(params);
			break;

		case 10: // sys_SetRegLongint
			// ACW 3/8/21 WIN-97
			sys_SetRegKey(params, selector); 
			break;

		case 11: // sys_SetRegLongint
			// ACW 3/9/21 WIN-99
			sys_SetRegKey(params, selector);
			break;

	}	
}

void InitPlugin()
{

	// WJF 9/1/15 #43731
	// ACW 10/28/20 WIN-107 Changed handleArray_init to initWindowManagement
	initWindowManagement();

}

void DeinitPlugin()
{
	// Write deinitialisation code here...
}




