//Win64API.h
/* --------------------------------------------------------------------------------
 #
 #	Win64API.h
 #	source generated by 4D Plugin Wizard
 #	Project : Win64API
 #	author : dwaddell
 #	10/2/2019
 #
 # --------------------------------------------------------------------------------*/

#include "Defines.h"

void InitPlugin();
void DeinitPlugin(PA_PluginParameters params);

